version: '3.7'

services:

  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud-data:/var/www/html
    ports:
      - '9696:80'
#    network_mode: "host"
    #environment:
    #  - POSGRESQL_PASSWORD=kflfrfkbyf118
    #  - POSGRESQL_DATABASE=nextcloud
    #  - POSGRESQL_USER=nextcloud
    #  - POSGRESQL_HOST=localhost
  
  proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
 #   restart: unless-stopped
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    network_mode: "host"
    volumes:
      - ./data:/data
#      - ./letsencrypt:/etc/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
